# Generated by Django 3.2.3 on 2021-05-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='counter_is',
            field=models.CharField(blank=True, max_length=242, null=True),
        ),
    ]
